CREATE TABLE Card (IdCard int4 NOT NULL, IdUser int4 NOT NULL, NameOfCard varchar(100) NOT NULL, CSV int4 NOT NULL, ExpiredDate date NOT NULL, PRIMARY KEY (IdCard, IdUser));
CREATE TABLE Category (Id SERIAL NOT NULL, Nombre varchar(30) NOT NULL, Description varchar(50), PRIMARY KEY (Id));
CREATE TABLE Chat (Id SERIAL NOT NULL, PRIMARY KEY (Id));
CREATE TABLE ChatLine (Id SERIAL NOT NULL, IdChat int4 NOT NULL, IdUser int4 NOT NULL, LineText text NOT NULL, WrittenDate timestamp NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Comment (Id SERIAL NOT NULL, IdJob int4 NOT NULL, IdUser int4 NOT NULL, IdCommentParent int4 DEFAULT 0 NOT NULL, Description varchar(255), "Date" timestamp, PRIMARY KEY (Id));
CREATE TABLE Employee (Id int4 NOT NULL, Ranking int4 NOT NULL, NumbJobsDone int4, PRIMARY KEY (Id));
CREATE TABLE Employee_Tag (IdEmployee int4 NOT NULL, IdTag int4 NOT NULL, PRIMARY KEY (IdEmployee, IdTag));
CREATE TABLE EmployeeJob (IdEmployee int4 NOT NULL, IdJob int4 NOT NULL, RankErE int4, RankEEr int4, Salary numeric(9, 2) NOT NULL, CounterOfer numeric(9, 2), State int4 NOT NULL, PRIMARY KEY (IdEmployee, IdJob));
CREATE TABLE EmployeeState (id SERIAL NOT NULL, description varchar(100) NOT NULL, PRIMARY KEY (id));
CREATE TABLE Employer (Id int4 NOT NULL, Ranking int4 NOT NULL, SpentAmount numeric(7, 2) NOT NULL, JobsPosted int4 NOT NULL, PRIMARY KEY (Id));
CREATE TABLE FavoritesJobs (IdEmployee int4 NOT NULL, IdJob int4 NOT NULL, PRIMARY KEY (IdEmployee, IdJob));
CREATE TABLE Followers (IdFollower int4 NOT NULL, IdFollowed int4 NOT NULL, PRIMARY KEY (IdFollower, IdFollowed));
CREATE TABLE Job (Id SERIAL NOT NULL, IdEmployeer int4 NOT NULL, Mode int4 NOT NULL, State int4 NOT NULL, IdLocation int4 NOT NULL, Title varchar(100) NOT NULL, Description varchar(500) NOT NULL, JobCost numeric(9, 2) NOT NULL, PhotoPath varchar(500) NOT NULL, DatePosted date NOT NULL, DateStart date NOT NULL, DateEnd date NOT NULL, DatePostEnd date NOT NULL, AvailablePercentage int4 NOT NULL, NumberApplicants int4 DEFAULT 1 NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Job_Tag (IdJob int4 NOT NULL, IdTag int4 NOT NULL, PRIMARY KEY (IdJob, IdTag));
CREATE TABLE JobAddress (IdJob int4 NOT NULL, Direction int4, Latitude numeric(10, 8), Longitude numeric(10, 8), PRIMARY KEY (IdJob));
CREATE TABLE JobMode (Id SERIAL NOT NULL, Mode varchar(20) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE JobState (Id SERIAL NOT NULL, State varchar(10) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Location (Id SERIAL NOT NULL, Country varchar(30) NOT NULL, City varchar(30) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE NationalIdentifierType (id SERIAL NOT NULL, description varchar(100) NOT NULL, PRIMARY KEY (id));
CREATE TABLE PaypalAccount (Id int4 NOT NULL, IdUser int4 NOT NULL, Email varchar(25), PRIMARY KEY (Id, IdUser));
CREATE TABLE Rankings (Id SERIAL NOT NULL, RankVal numeric(2, 1) NOT NULL, PRIMARY KEY (Id));
CREATE TABLE "Tag" (Id SERIAL NOT NULL, Name varchar(50) NOT NULL, Description varchar(100), CategoryId int4 NOT NULL, PRIMARY KEY (Id));
CREATE TABLE Transactions (id SERIAL NOT NULL, idUser int4 NOT NULL, Idtype int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE TypeOfTransactions (id SERIAL NOT NULL, name int4 NOT NULL, description int4 NOT NULL, PRIMARY KEY (id));
CREATE TABLE "User" (Id SERIAL NOT NULL, Id_Location int4 NOT NULL, IdState int4 NOT NULL, TypeNationalIdentifier int4 NOT NULL, NationalIdentifier int4 NOT NULL UNIQUE, Name varchar(30) NOT NULL, LastName varchar(30) NOT NULL, Email varchar(30) NOT NULL UNIQUE, Password varchar(15) NOT NULL, BirthDate date NOT NULL, Direction varchar(255), Gender char(1) NOT NULL, Nationality varchar(30) NOT NULL, AvailableMoney numeric(9, 2) NOT NULL, Nonce varchar(10) NOT NULL UNIQUE, PRIMARY KEY (Id));
CREATE TABLE UserStaff (IdUser int4 NOT NULL, About varchar(500) NOT NULL, PhotoPath varchar(225) NOT NULL, Cellphone varchar(20) NOT NULL, PRIMARY KEY (IdUser));
CREATE TABLE UserState (Id SERIAL NOT NULL, State varchar(10) NOT NULL, PRIMARY KEY (Id));
ALTER TABLE "User" ADD CONSTRAINT FKUser370675 FOREIGN KEY (Id_Location) REFERENCES Location (Id);
ALTER TABLE Employee ADD CONSTRAINT FKEmployee765723 FOREIGN KEY (Id) REFERENCES "User" (Id);
ALTER TABLE Employee_Tag ADD CONSTRAINT FKEmployee_T885701 FOREIGN KEY (IdEmployee) REFERENCES Employee (Id);
ALTER TABLE Employee_Tag ADD CONSTRAINT FKEmployee_T146168 FOREIGN KEY (IdTag) REFERENCES "Tag" (Id);
ALTER TABLE Employer ADD CONSTRAINT FKEmployer765736 FOREIGN KEY (Id) REFERENCES "User" (Id);
ALTER TABLE Employer ADD CONSTRAINT FKEmployer755455 FOREIGN KEY (Ranking) REFERENCES Rankings (Id);
ALTER TABLE Employee ADD CONSTRAINT FKEmployee755468 FOREIGN KEY (Ranking) REFERENCES Rankings (Id);
ALTER TABLE Job ADD CONSTRAINT FKJob21280 FOREIGN KEY (Mode) REFERENCES JobMode (Id);
ALTER TABLE Job ADD CONSTRAINT FKJob218444 FOREIGN KEY (State) REFERENCES JobState (Id);
ALTER TABLE Job ADD CONSTRAINT FKJob67976 FOREIGN KEY (IdEmployeer) REFERENCES Employer (Id);
ALTER TABLE EmployeeJob ADD CONSTRAINT FKEmployeeJo204629 FOREIGN KEY (IdEmployee) REFERENCES Employee (Id);
ALTER TABLE EmployeeJob ADD CONSTRAINT FKEmployeeJo483457 FOREIGN KEY (IdJob) REFERENCES Job (Id);
ALTER TABLE Job_Tag ADD CONSTRAINT FKJob_Tag598555 FOREIGN KEY (IdJob) REFERENCES Job (Id);
ALTER TABLE Job_Tag ADD CONSTRAINT FKJob_Tag616917 FOREIGN KEY (IdTag) REFERENCES "Tag" (Id);
ALTER TABLE Job ADD CONSTRAINT FKJob50815 FOREIGN KEY (IdLocation) REFERENCES Location (Id);
ALTER TABLE "User" ADD CONSTRAINT FKUser467300 FOREIGN KEY (IdState) REFERENCES UserState (Id);
ALTER TABLE Comment ADD CONSTRAINT FKComment369264 FOREIGN KEY (IdJob) REFERENCES Job (Id);
ALTER TABLE Comment ADD CONSTRAINT FKComment659526 FOREIGN KEY (IdUser) REFERENCES "User" (Id);
ALTER TABLE Comment ADD CONSTRAINT FKComment218269 FOREIGN KEY (IdCommentParent) REFERENCES Comment (Id);
ALTER TABLE UserStaff ADD CONSTRAINT FKUserStaff12578 FOREIGN KEY (IdUser) REFERENCES "User" (Id);
ALTER TABLE JobAddress ADD CONSTRAINT FKJobAddress850771 FOREIGN KEY (IdJob) REFERENCES Job (Id);
ALTER TABLE ChatLine ADD CONSTRAINT FKChatLine684908 FOREIGN KEY (IdChat) REFERENCES Chat (Id);
ALTER TABLE ChatLine ADD CONSTRAINT FKChatLine591045 FOREIGN KEY (IdUser) REFERENCES "User" (Id);
ALTER TABLE "Tag" ADD CONSTRAINT FKTag730765 FOREIGN KEY (CategoryId) REFERENCES Category (Id);
ALTER TABLE EmployeeJob ADD CONSTRAINT FKEmployeeJo623179 FOREIGN KEY (State) REFERENCES EmployeeState (id);
ALTER TABLE "User" ADD CONSTRAINT FKUser977272 FOREIGN KEY (TypeNationalIdentifier) REFERENCES NationalIdentifierType (id);
ALTER TABLE FavoritesJobs ADD CONSTRAINT FKFavoritesJ937340 FOREIGN KEY (IdEmployee) REFERENCES Employee (Id);
ALTER TABLE FavoritesJobs ADD CONSTRAINT FKFavoritesJ658512 FOREIGN KEY (IdJob) REFERENCES Job (Id);
ALTER TABLE Followers ADD CONSTRAINT FKFollowers571517 FOREIGN KEY (IdFollower) REFERENCES "User" (Id);
ALTER TABLE Followers ADD CONSTRAINT FKFollowers571503 FOREIGN KEY (IdFollowed) REFERENCES "User" (Id);
ALTER TABLE Transactions ADD CONSTRAINT FKTransactio343446 FOREIGN KEY (Idtype) REFERENCES TypeOfTransactions (id);

